version: '3.3'
services:
  osoolAlDeyafah:
    image: osoolaldeyafah
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: osoolAlDeyafah
      MONGO_INITDB_ROOT_PASSWORD: osoolAlDeyafah
    container_name:
      mymongo
    ports:
      - "27017:27017"
    volumes:
      - "/mongodb:/data/db"
    networks:
      - backend
volumes:
  mongodb:
networks:
  backend: